model_name: "llava-v1.5-7b"
num_layers: 32
layer_module_tmp: "language_model.model.layers.{}"
mlp_module_tmp: "language_model.model.layers.{}.mlp"
attn_module_tmp: "language_model.model.layers.{}.self_attn"
vproj_module_tmp: "language_model.model.layers.{}.self_attn.v_proj"
kvproj_module_tmp: "language_model.model.layers.{}.self_attn.k_proj"
qproj_module_tmp: "language_model.model.layers.{}.self_attn.q_proj"
oproj_module_tmp: "language_model.model.layers.{}.self_attn.o_proj"
norm_path: "language_model.model.norm"
voc_path: "language_model.lm_head"
